import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Link from 'next/link'
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Zulu Vision</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="layout">
        <section className={styles["home_bg_body"]}>
          <main>
            <Image
              src={
                "https://firebasestorage.googleapis.com/v0/b/zulu-vision.appspot.com/o/459900110001.jpg?alt=media&token=59ffe85b-0d25-4cab-9803-bf16fb7916ba"
              }
              className={styles.hero_bg}
              objectPosition="center"
              layout="fill"
              objectFit="cover"
              alt=""
            />
            <div className={styles.container}>
              <Link className="hero_area" href="/portfolio">
                <h1 className="lg:text-9xl text-4xl ">
                  欢迎 Zulu Vision 来到
                </h1>
                <span className="hero_area__top"></span>
                <span className="hero_area__right"></span>
                <span className="hero_area__bottom"></span>
                <span className="hero_area__left"></span>
              </Link>
            </div>
          </main>
        </section>
      </div>
    </>
  );
}
