import Navigation from "@/components/navigation/navigation";
import Parallax from "@/components/parallax/Parallax";
import Head from "next/head";


const Portfolio = () => {
    const heading = [
        { text: "Welcome to Zulu Vision", delay: 3000 },
        { text: "Location: Spain alleyway", delay: 4000 },
    ]
    return (
      <div>
        <Head>
          <title>Zulu Vision</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="layout">
          <section className="wrapper">
            <Parallax
              imgUrl="https://firebasestorage.googleapis.com/v0/b/zulu-vision.appspot.com/o/portfolio%2F459900050002.jpg?alt=media&token=d8b413ce-383a-4916-9a37-c4490bf55b4c"
              headings={heading}
            />
            <Parallax
              imgUrl="https://firebasestorage.googleapis.com/v0/b/zulu-vision.appspot.com/o/portfolio%2F459900070006.jpg?alt=media&token=f9fe4075-0b82-466a-97ea-dc2bd5cf8f33"
              headings={heading}
            />
            <Parallax
              imgUrl="https://firebasestorage.googleapis.com/v0/b/zulu-vision.appspot.com/o/portfolio%2F459900110001.jpg?alt=media&token=623b9fbb-7a90-4e8f-a540-89be89c7fa19"
              headings={heading}
            />
            <Parallax
              imgUrl="https://firebasestorage.googleapis.com/v0/b/zulu-vision.appspot.com/o/portfolio%2F459900110002.jpg?alt=media&token=f7e58331-de90-4016-9b71-d8d0af8cce01"
              headings={heading}
            />
          </section>
        </div>
      </div>
    );
}
 
export default Portfolio;