import Navigation from "@/components/navigation/navigation";
import Parallax from "@/components/parallax/Parallax";
import Head from "next/head";


const Portfolio = () => {
    const heading = [
        { text: "Welcome to Zulu Vision", delay: 3000 },
        { text: "Location: Spain alleyway", delay: 4000 },
    ]
    return ( <div>
        <Head>
          <title>Zulu Vision</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='layout'>
          <section className="wrapper">
            <Parallax imgUrl="/img/459900050002.jpg" headings={ heading }/>
            <Parallax imgUrl="/img/459900070006.jpg" headings={ heading } />
            <Parallax imgUrl="/img/459900110001.jpg" headings={ heading } />
            <Parallax imgUrl="/img/459900110002.jpg" headings={ heading } />
          </section>
        </div>
    </div> );
}
 
export default Portfolio;